const express = require('express');
const cors = require('cors');
const { port } = require('./config/config');
const authRoutes = require('./routes/authRoutes');
const dashboardRoutes = require('./routes/dashboardRoutes');
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/auth', authRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use((error, req, res, next) => { console.error(error); res.status(500).json({ message: 'An unexpected server error occurred.' }); });
app.listen(port, () => console.log(`API server listening on port ${port}`));